### ISSUE TITLE
(JS-0085) Found some variables redeclared

### ISSUE THREAD

**Issue by lovetyagi-17** [Khoding/khoBlog#26]
## Description
In JavaScript, it&#x27;s possible to redeclare the same variable name using `var`. This can lead to confusion as to where the variable is actually declared and initialized. Example - The not-preferred way :

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Khoding/khoBlog/issue/JS-0085/occurrences/](https://deepsource.io/gh/Khoding/khoBlog/issue/JS-0085/occurrences/)

**Comment by lovetyagi-17** [comment]
I am working on this #26

**Comment by Khoding** [comment]
Damn my first issue by someone who isn't a bot 😄 

I'm aware that this script is broken in a lot of ways, I'm actually thinking about digging it and fixing all the problems with it.

It wasn't made by me, I just found it on a website that was about to be shut down, so I decided to save it for myself because I liked it.

Although as far as I know the said website still hasn't been shut down... so yeah 😂 

You can fix it if you want, else I'll try to explore it and actually read the whole code, and then fix the issues some times in the next few weeks.

**Comment by Khoding** [comment]
Closed at a1bbf6b25b151bc5351317261a46af85b8c59775
File removed
